### PR TITLE
fix keyword

### PR DESCRIPTION
**Pull request by ghost**
I think that "automation" is more correct

### CODE REVIEW

**Comment by iamstarkov** [comment]
Valid note. Also due to Wiktionary _[Automation](https://en.wiktionary.org/wiki/automation)_ have _automatization, automatisation_ sinonyms. What do you think about not replacing but adding?

**Comment by ghost** [comment]
Ok

**Comment by ghost** [comment]
Most npm modules use "automation"
https://www.npmjs.com/browse/keyword/automation

**Comment by iamstarkov** [comment]
I understand. Thanks =)

**Pull request merged**
