### PR TITLE
Promisify

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by iamstarkov** [comment]
if you dont mind i would like to add you to this project as well. what do you think?

**Comment by iamstarkov** [comment]
published as v4

**Comment by iamstarkov** [comment]
thank you very much

**Comment by ghost** [comment]
:clap:

**Comment by ghost** [comment]
> if you dont mind i would like to add you to this project as well. what do you think?

Thanks, I'm glad to help

**Pull request merged**
